//Cart
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const CALC_POSTAL_PRICE = 'CALC_POSTAL_PRICE'
export const CALC_TOTAL_PRICE = 'CALC_TOTAL_PRICE'
export const CALC_SUBTOTAL_PRICE = 'CALC_SUBTOTAL_PRICE'
